### ISSUE TITLE
Parallel Execution MPI Fails

### ISSUE THREAD

**Issue by marcelned** [Bodo-inc/Feedback#2]
**Environment:**

MacOS Monterey, Conda, Python 3.9

**Please see error logs on executing `mpiexec -n 8 python bodo_data_transform.py`**

```console
[mpiexec@...] HYDU_parse_hostfile (utils/args/args.c:316): unable to open host file: hostfile
[mpiexec@] mfile_fn (ui/mpich/utils.c:325): error parsing hostfile
[mpiexec@] match_arg (utils/args/args.c:153): match handler returned error
[mpiexec@] HYDU_parse_array (utils/args/args.c:175): argument matching returned error
[mpiexec@] parse_args (ui/mpich/utils.c:1603): error parsing input array
[mpiexec@] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1655): unable to parse user arguments
[mpiexec@] main (ui/mpich/mpiexec.c:128): error parsing parameters
```

**Comment by ehsantn** [comment]
@marcelned Looks like mpiexec is expecting a hostfile for some reason. You could create a text file named "hostfile" in current directory with just "localhost" in it. Then `mpiexec --hostfile hostfile -n 8 python bodo_data_transform.py` should probably work. Could you try this and let me me know?

**Comment by marcelned** [comment]
Thanks @ehsantn, despite a `[WARNING] yaksa: 2 leaked handle pool objects` message, it works now.
