### ISSUE TITLE
Enterprise Documentation 

### ISSUE THREAD

**Issue by Pipboyguy** [Bodo-inc/Feedback#3]
In https://docs.bodo.ai/latest/source/installation_and_setup/enterprise.html:

```console
export BODO_LICENSE=`cat bodo.lic
```

should be 

```console
export BODO_LICENSE=`cat bodo.lic`
```

**Comment by ehsantn** [comment]
Thanks for reporting this @Pipboyguy! We will fix this soon. We are actually revamping our docs.

cc @ritwika314
